package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/asheshgoplani/agent-deck/internal/session"
)

// envVarFlags implements flag.Value for repeatable -env KEY=VALUE flags
type envVarFlags map[string]string

func (e *envVarFlags) String() string { return "" }
func (e *envVarFlags) Set(val string) error {
	parts := strings.SplitN(val, "=", 2)
	if len(parts) != 2 || parts[0] == "" {
		return fmt.Errorf("invalid env format %q, expected KEY=VALUE", val)
	}
	(*e)[parts[0]] = parts[1]
	return nil
}

// handleConductor dispatches conductor subcommands
func handleConductor(profile string, args []string) {
	if len(args) == 0 {
		printConductorHelp()
		return
	}

	switch args[0] {
	case "setup":
		handleConductorSetup(profile, args[1:])
	case "teardown":
		handleConductorTeardown(profile, args[1:])
	case "status":
		handleConductorStatus(profile, args[1:])
	case "list":
		handleConductorList(profile, args[1:])
	case "move":
		handleConductorMove(profile, args[1:])
	case "migrate-dir":
		handleConductorMigrateDir(profile, args[1:])
	case "help", "--help", "-h":
		printConductorHelp()
	default:
		fmt.Fprintf(os.Stderr, "Unknown conductor command: %s\n", args[0])
		fmt.Fprintln(os.Stderr)
		printConductorHelp()
		os.Exit(1)
	}
}

// runAutoMigration runs legacy conductor migration and prints results
func runAutoMigration(jsonOutput bool) {
	migratedLegacy, err := session.MigrateLegacyConductors()
	if err != nil && !jsonOutput {
		fmt.Fprintf(os.Stderr, "Warning: migration check failed: %v\n", err)
	}

	migratedPolicy, err := session.MigrateConductorPolicySplit()
	if err != nil && !jsonOutput {
		fmt.Fprintf(os.Stderr, "Warning: policy migration check failed: %v\n", err)
	}

	migratedLearnings, err := session.MigrateConductorLearnings()
	if err != nil && !jsonOutput {
		fmt.Fprintf(os.Stderr, "Warning: learnings migration check failed: %v\n", err)
	}

	migratedHeartbeatScripts, err := session.MigrateConductorHeartbeatScripts()
	if err != nil && !jsonOutput {
		fmt.Fprintf(os.Stderr, "Warning: heartbeat script migration check failed: %v\n", err)
	}

	if !jsonOutput {
		for _, name := range migratedLegacy {
			fmt.Printf("  [migrated] Legacy conductor: %s\n", name)
		}
		for _, name := range migratedPolicy {
			fmt.Printf("  [migrated] Updated policy split: %s\n", name)
		}
		for _, name := range migratedLearnings {
			fmt.Printf("  [migrated] Added learnings: %s\n", name)
		}
		for _, name := range migratedHeartbeatScripts {
			// The rendered script self-heals here, but the launchd plist /
			// systemd unit bakes the old absolute paths and is only
			// regenerated by 'conductor setup'. Warn instead of implying full
			// reconciliation. Detection is side-effect-free (no launchctl).
			if session.HeartbeatDaemonStale(name) {
				fmt.Printf("  [migrated] Refreshed heartbeat script: %s (heartbeat daemon may be stale — run 'agent-deck conductor setup %s' to reload)\n", name, name)
			} else {
				fmt.Printf("  [migrated] Refreshed heartbeat script: %s\n", name)
			}
		}
	}
}

// parseConductorSetupArgs parses setup flags and returns the conductor name and any extra positional args.
func parseConductorSetupArgs(fs *flag.FlagSet, args []string) (string, []string, error) {
	if err := fs.Parse(normalizeArgs(fs, args)); err != nil {
		return "", nil, err
	}
	remaining := fs.Args()
	if len(remaining) == 0 {
		return "", nil, nil
	}
	return remaining[0], remaining[1:], nil
}

func yesAnswer(s string) bool { return s == "y" || s == "yes" }

// handleConductorSetup sets up a named conductor with directories, sessions, and optionally the Telegram bridge
func handleConductorSetup(profile string, args []string) {
	fs := flag.NewFlagSet("conductor setup", flag.ExitOnError)
	agent := fs.String("agent", session.ConductorAgentClaude, "Conductor agent runtime (claude or codex)")
	noClearOnCompact := fs.Bool("no-clear-on-compact", false, "Claude-only: allow normal compaction instead of /clear when context fills up")
	description := fs.String("description", "", "Description for this conductor")
	heartbeat := fs.Bool("heartbeat", false, "Enable heartbeat for this conductor (default)")
	noHeartbeat := fs.Bool("no-heartbeat", false, "Disable heartbeat for this conductor")
	heartbeatIdleMinutes := fs.Int("heartbeat-idle-minutes", 0, "Minutes of idle time before pausing heartbeats (default 0=disabled, negative also disabled)")
	instructionsMD := fs.String("instructions-md", "", "Custom instructions file for this conductor (agent-specific, e.g., ~/docs/conductor-ops.md)")
	sharedInstructionsMD := fs.String("shared-instructions-md", "", "Custom shared instructions file for all conductors of this agent")
	claudeMD := fs.String("claude-md", "", "Custom CLAUDE.md for this conductor (e.g., ~/docs/conductor-ryan.md)")
	policyMD := fs.String("policy-md", "", "Custom POLICY.md for this conductor (e.g., ~/docs/my-policy.md)")
	heartbeatRulesMD := fs.String("heartbeat-rules-md", "", "Custom HEARTBEAT_RULES.md for this conductor (e.g., ~/docs/my-heartbeat-rules.md)")
	sharedClaudeMD := fs.String("shared-claude-md", "", "Custom path for shared CLAUDE.md (e.g., ~/docs/conductor-shared.md)")
	sharedPolicyMD := fs.String("shared-policy-md", "", "Custom path for shared POLICY.md (e.g., ~/docs/conductor-policy.md)")
	envFile := fs.String("env-file", "", "Path to .env file to source before conductor starts (e.g., ~/.conductor.env)")
	envFlags := make(envVarFlags)
	fs.Var(&envFlags, "env", "Environment variable in KEY=VALUE format (can be repeated)")
	jsonOutput := fs.Bool("json", false, "Output as JSON")

	fs.Usage = func() {
		fmt.Println("Usage: agent-deck [-p profile] conductor setup <name> [options]")
		fmt.Println()
		fmt.Println("Set up a named conductor: creates its directory, instructions file, meta.json, and session registration.")
		fmt.Println("Multiple conductors can exist per profile.")
		fmt.Println()
		fmt.Println("Arguments:")
		fmt.Println("  <name>    Conductor name (e.g., ryan, infra, monitor)")
		fmt.Println()
		fmt.Println("Options:")
		fmt.Println("  -agent string")
		fmt.Println("        Conductor agent runtime: claude or codex (default \"claude\")")
		fmt.Println("  -description string")
		fmt.Println("        Description for this conductor")
		fmt.Println("  -heartbeat")
		fmt.Println("        Enable heartbeat for this conductor (default)")
		fmt.Println("  -no-heartbeat")
		fmt.Println("        Disable heartbeat for this conductor")
		fmt.Println("  -heartbeat-idle-minutes int")
		fmt.Println("        Minutes of idle time before pausing heartbeats (default 0=disabled, negative also disabled)")
		fmt.Println("  -no-clear-on-compact")
		fmt.Println("        Claude-only: allow normal compaction instead of /clear when context fills up")
		fmt.Println()
		fmt.Println("Conductor-specific files:")
		fmt.Println("  -instructions-md string")
		fmt.Println("        Custom instructions file for this conductor (agent-specific)")
		fmt.Println("  -claude-md string")
		fmt.Println("        Deprecated Claude-only alias for -instructions-md")
		fmt.Println("  -policy-md string")
		fmt.Println("        Custom POLICY.md for this conductor (e.g., ~/docs/my-policy.md)")
		fmt.Println("  -heartbeat-rules-md string")
		fmt.Println("        Custom HEARTBEAT_RULES.md for this conductor (e.g., ~/docs/my-heartbeat-rules.md)")
		fmt.Println()
		fmt.Println("Shared files (all conductors):")
		fmt.Println("  -shared-instructions-md string")
		fmt.Println("        Custom shared instructions file for all conductors of this agent")
		fmt.Println("  -shared-claude-md string")
		fmt.Println("        Deprecated Claude-only alias for -shared-instructions-md")
		fmt.Println("  -shared-policy-md string")
		fmt.Println("        Custom path for shared POLICY.md (e.g., ~/docs/conductor-policy.md)")
		fmt.Println()
		fmt.Println("Environment:")
		fmt.Println("  -env KEY=VALUE")
		fmt.Println("        Environment variable for the conductor session (can be repeated)")
		fmt.Println("  -env-file string")
		fmt.Println("        Path to .env file to source before conductor starts")
		fmt.Println()
		fmt.Println("Output:")
		fmt.Println("  -json")
		fmt.Println("        Output as JSON")
	}

	name, extras, err := parseConductorSetupArgs(fs, args)
	if err != nil {
		os.Exit(1)
	}

	if name == "" {
		fmt.Fprintln(os.Stderr, "Error: conductor name is required")
		fmt.Fprintln(os.Stderr, "Usage: agent-deck [-p profile] conductor setup <name>")
		os.Exit(1)
	}
	if len(extras) > 0 {
		fmt.Fprintf(os.Stderr, "Error: unexpected arguments: %s\n", strings.Join(extras, " "))
		os.Exit(1)
	}

	if err := session.ValidateConductorName(name); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
	spec, err := session.GetConductorAgentSpec(*agent)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
	if *instructionsMD != "" && *claudeMD != "" {
		fmt.Fprintln(os.Stderr, "Error: use only one of -instructions-md or -claude-md")
		os.Exit(1)
	}
	if *sharedInstructionsMD != "" && *sharedClaudeMD != "" {
		fmt.Fprintln(os.Stderr, "Error: use only one of -shared-instructions-md or -shared-claude-md")
		os.Exit(1)
	}
	resolvedInstructionsMD := *instructionsMD
	if resolvedInstructionsMD == "" {
		resolvedInstructionsMD = *claudeMD
	}
	resolvedSharedInstructionsMD := *sharedInstructionsMD
	if resolvedSharedInstructionsMD == "" {
		resolvedSharedInstructionsMD = *sharedClaudeMD
	}
	if spec.Agent != session.ConductorAgentClaude && (*claudeMD != "" || *sharedClaudeMD != "") {
		fmt.Fprintln(os.Stderr, "Error: -claude-md and -shared-claude-md are only valid with --agent=claude")
		os.Exit(1)
	}
	resolvedProfile := session.GetEffectiveProfile(profile)

	// Auto-migrate legacy conductors
	runAutoMigration(*jsonOutput)

	// Determine heartbeat setting (on by default; --no-heartbeat disables, --heartbeat re-confirms)
	heartbeatEnabled := !*noHeartbeat || *heartbeat

	// Step 1: Load config and check if conductor system is enabled
	config, err := session.LoadUserConfig()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error loading config: %v\n", err)
		os.Exit(1)
	}

	settings := config.Conductor
	// Token presence is sufficient: the wizard saves atomically after collecting
	// all fields, so a token implies a complete config for that channel.
	telegramConfigured := settings.Telegram.Token != ""
	slackConfigured := settings.Slack.BotToken != ""
	discordConfigured := settings.Discord.BotToken != ""

	// v1.7.22: warn on the "global telegram enabled in profile settings.json"
	// anti-pattern that silently leaks pollers to every claude session under
	// this profile. We detect but do not auto-mutate settings.json (#658).
	cfgDir := config.GetProfileClaudeConfigDir(resolvedProfile)
	if cfgDir == "" {
		cfgDir = session.GetClaudeConfigDirForGroup("")
	}
	if globalTelegramEnabled, _ := readTelegramGloballyEnabled(cfgDir); globalTelegramEnabled {
		emitTelegramWarnings(os.Stderr, session.TelegramValidatorInput{
			GlobalEnabled: true,
		})
		// Issue #666: the v1.7.22 warn-only path was insufficient. Users
		// missed the warning and kept losing generic child sessions to 409
		// crashes. Auto-remediate so every profile that setup touches is
		// left safe.
		if changed, err := disableTelegramGlobally(cfgDir); err != nil {
			fmt.Fprintf(os.Stderr, "⚠  could not auto-disable enabledPlugins.telegram in %s/settings.json: %v\n", cfgDir, err)
		} else if changed {
			fmt.Fprintf(os.Stdout, "✓ Auto-disabled enabledPlugins.\"%s\" in %s/settings.json (issue #666 remediation)\n", "telegram@claude-plugins-official", cfgDir)
		}
	}

	// Step 2a: First-time intro (only shown when no conductors exist yet).
	if !*jsonOutput && !session.ConductorSystemActive() {
		fmt.Println("Conductor Setup")
		fmt.Println("===============")
		fmt.Println()
		fmt.Printf("The conductor system lets you create named persistent %s conductor sessions that\n", spec.DisplayName)
		fmt.Println("monitor and orchestrate all your agent-deck sessions.")
		fmt.Println()
		fmt.Println("Conductors work locally by default — interact via the TUI or CLI.")
		fmt.Println("You can optionally connect remote channels (Telegram, Slack, Discord)")
		fmt.Println("for mobile and remote access.")
		fmt.Println()
	}

	// Step 2b: Offer channel configuration for any unconfigured channels.
	// Runs on first setup and on re-runs, so users can add channels later.
	// Skipped in --json mode: interactive prompts would hang on stdin.
	if !*jsonOutput && (!telegramConfigured || !slackConfigured || !discordConfigured) {
		reader := bufio.NewReader(os.Stdin)

		fmt.Print("Add remote channels for mobile/remote access? (y/N): ")
		channelAnswer, _ := reader.ReadString('\n')
		channelAnswer = strings.TrimSpace(strings.ToLower(channelAnswer))

		if yesAnswer(channelAnswer) {
			configChanged := false

			if !telegramConfigured {
				fmt.Print("Connect Telegram bot for mobile control? (y/N): ")
				tgAnswer, _ := reader.ReadString('\n')
				tgAnswer = strings.TrimSpace(strings.ToLower(tgAnswer))

				if yesAnswer(tgAnswer) {
					fmt.Println()
					fmt.Println("  1. Message @BotFather on Telegram -> /newbot -> copy the token")
					fmt.Println("  2. Message @userinfobot on Telegram -> copy your user ID")
					fmt.Println()

					fmt.Print("Telegram bot token: ")
					token, _ := reader.ReadString('\n')
					token = strings.TrimSpace(token)
					if token == "" {
						fmt.Fprintln(os.Stderr, "Error: token is required")
						os.Exit(1)
					}

					fmt.Print("Your Telegram user ID: ")
					userIDStr, _ := reader.ReadString('\n')
					userIDStr = strings.TrimSpace(userIDStr)
					userID, err := strconv.ParseInt(userIDStr, 10, 64)
					if err != nil || userID == 0 {
						fmt.Fprintln(os.Stderr, "Error: valid user ID is required")
						os.Exit(1)
					}

					settings.Telegram = session.TelegramSettings{Token: token, UserID: userID}
					configChanged = true
				}
			}

			if !slackConfigured {
				fmt.Print("Connect Slack bot for channel-based control? (y/N): ")
				slackAnswer, _ := reader.ReadString('\n')
				slackAnswer = strings.TrimSpace(strings.ToLower(slackAnswer))

				if yesAnswer(slackAnswer) {
					fmt.Println()
					fmt.Println("  1. Create a Slack app at https://api.slack.com/apps")
					fmt.Println("  2. Enable Socket Mode -> generate an app-level token (xapp-...)")
					fmt.Println("  3. Add bot scopes: chat:write, channels:history, channels:read, app_mentions:read")
					fmt.Println("  4. Enable Event Subscriptions -> subscribe to bot events: message.channels, app_mention")
					fmt.Println("  5. Install the app to your workspace")
					fmt.Println("  6. Invite the bot to your channel (/invite @botname)")
					fmt.Println()

					fmt.Print("Slack bot token (xoxb-...): ")
					botToken, _ := reader.ReadString('\n')
					botToken = strings.TrimSpace(botToken)
					if botToken == "" {
						fmt.Fprintln(os.Stderr, "Error: bot token is required")
						os.Exit(1)
					}

					fmt.Print("Slack app token (xapp-...): ")
					appToken, _ := reader.ReadString('\n')
					appToken = strings.TrimSpace(appToken)
					if appToken == "" {
						fmt.Fprintln(os.Stderr, "Error: app token is required")
						os.Exit(1)
					}

					fmt.Print("Slack channel ID (C01234...): ")
					channelID, _ := reader.ReadString('\n')
					channelID = strings.TrimSpace(channelID)
					if channelID == "" {
						fmt.Fprintln(os.Stderr, "Error: channel ID is required")
						os.Exit(1)
					}

					settings.Slack = session.SlackSettings{BotToken: botToken, AppToken: appToken, ChannelID: channelID}
					configChanged = true
				}
			}

			if !discordConfigured {
				fmt.Print("Connect Discord bot for channel-based control? (y/N): ")
				dcAnswer, _ := reader.ReadString('\n')
				dcAnswer = strings.TrimSpace(strings.ToLower(dcAnswer))

				if yesAnswer(dcAnswer) {
					fmt.Println()
					fmt.Println("  1. Create an application at https://discord.com/developers/applications")
					fmt.Println("  2. Bot tab -> create bot, copy the token")
					fmt.Println("  3. Enable MESSAGE CONTENT intent in the Bot tab")
					fmt.Println("  4. OAuth2 -> URL Generator: scopes=[bot, applications.commands],")
					fmt.Println("     permissions=[Send Messages, Read Message History]")
					fmt.Println("  5. Invite bot to your server using the generated URL")
					fmt.Println()

					fmt.Print("Discord bot token: ")
					dcBotToken, _ := reader.ReadString('\n')
					dcBotToken = strings.TrimSpace(dcBotToken)
					if dcBotToken == "" {
						fmt.Fprintln(os.Stderr, "Error: bot token is required")
						os.Exit(1)
					}

					fmt.Print("Discord guild (server) ID: ")
					dcGuildIDStr, _ := reader.ReadString('\n')
					dcGuildIDStr = strings.TrimSpace(dcGuildIDStr)
					dcGuildID, err := strconv.ParseInt(dcGuildIDStr, 10, 64)
					if err != nil || dcGuildID == 0 {
						fmt.Fprintln(os.Stderr, "Error: valid guild ID is required")
						os.Exit(1)
					}

					fmt.Print("Discord channel ID: ")
					dcChannelIDStr, _ := reader.ReadString('\n')
					dcChannelIDStr = strings.TrimSpace(dcChannelIDStr)
					dcChannelID, err := strconv.ParseInt(dcChannelIDStr, 10, 64)
					if err != nil || dcChannelID == 0 {
						fmt.Fprintln(os.Stderr, "Error: valid channel ID is required")
						os.Exit(1)
					}

					fmt.Print("Your Discord user ID: ")
					dcUserIDStr, _ := reader.ReadString('\n')
					dcUserIDStr = strings.TrimSpace(dcUserIDStr)
					dcUserID, err := strconv.ParseInt(dcUserIDStr, 10, 64)
					if err != nil || dcUserID == 0 {
						fmt.Fprintln(os.Stderr, "Error: valid user ID is required")
						os.Exit(1)
					}

					settings.Discord = session.DiscordSettings{BotToken: dcBotToken, GuildID: dcGuildID, ChannelID: dcChannelID, UserID: dcUserID}
					configChanged = true
				}
			}

			if configChanged {
				if settings.HeartbeatInterval == nil {
					heartbeatDefault := 15
					settings.HeartbeatInterval = &heartbeatDefault
				}
				config.Conductor = settings

				telegramConfigured = settings.Telegram.Token != ""
				slackConfigured = settings.Slack.BotToken != ""
				discordConfigured = settings.Discord.BotToken != ""

				if err := session.SaveUserConfig(config); err != nil {
					fmt.Fprintf(os.Stderr, "Error saving config: %v\n", err)
					os.Exit(1)
				}
				fmt.Println()
				fmt.Println("[ok] Conductor config saved to config.toml")
			}
		}
	}

	// Ensure heartbeat interval is defaulted regardless of channel config path.
	if heartbeatEnabled && settings.HeartbeatInterval == nil {
		heartbeatDefault := 15
		settings.HeartbeatInterval = &heartbeatDefault
		config.Conductor = settings
		if err := session.SaveUserConfig(config); err != nil {
			fmt.Fprintf(os.Stderr, "Error saving config: %v\n", err)
			os.Exit(1)
		}
	}

	// Step 3: Install/update shared instructions file for the selected agent
	if err := session.InstallSharedConductorInstructions(spec.Agent, resolvedSharedInstructionsMD); err != nil {
		fmt.Fprintf(os.Stderr, "Error installing shared %s: %v\n", spec.InstructionsFileName, err)
		os.Exit(1)
	}
	if !*jsonOutput {
		fmt.Printf("[ok] Shared %s installed/updated\n", spec.InstructionsFileName)
	}

	// Step 3b: Install/update shared POLICY.md
	if err := session.InstallPolicyMD(*sharedPolicyMD); err != nil {
		fmt.Fprintf(os.Stderr, "Error installing POLICY.md: %v\n", err)
		os.Exit(1)
	}
	if !*jsonOutput {
		fmt.Println("[ok] Shared POLICY.md installed/updated")
	}

	// Step 3c: Install shared LEARNINGS.md (don't overwrite existing)
	if err := session.InstallLearningsMD(); err != nil {
		fmt.Fprintf(os.Stderr, "Error installing LEARNINGS.md: %v\n", err)
		os.Exit(1)
	}
	if !*jsonOutput {
		fmt.Println("[ok] Shared LEARNINGS.md installed")
	}

	// Step 4: Set up the named conductor
	if !*jsonOutput {
		fmt.Printf("\nSetting up conductor: %s (profile: %s)\n", name, resolvedProfile)
	}

	clearOnCompact := !*noClearOnCompact
	if !spec.SupportsClearOnCompact {
		clearOnCompact = false
	}
	var envMap map[string]string
	if len(envFlags) > 0 {
		envMap = map[string]string(envFlags)
	}
	if err := session.SetupConductorWithAgent(name, resolvedProfile, spec.Agent, heartbeatEnabled, clearOnCompact, *description, resolvedInstructionsMD, *policyMD, *heartbeatRulesMD, envMap, *envFile, *heartbeatIdleMinutes); err != nil {
		fmt.Fprintf(os.Stderr, "Error setting up conductor %s: %v\n", name, err)
		os.Exit(1)
	}
	if !*jsonOutput {
		fmt.Printf("  [ok] Directory, %s, and meta.json created\n", spec.InstructionsFileName)
	}

	// Step 5: Register session in the profile's storage
	sessionTitle := session.ConductorSessionTitle(name)
	storage, err := session.NewStorageWithProfile(resolvedProfile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error loading storage for %s: %v\n", resolvedProfile, err)
		os.Exit(1)
	}

	instances, groups, err := storage.LoadWithGroups()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error loading sessions for %s: %v\n", resolvedProfile, err)
		os.Exit(1)
	}

	// Check if session already exists
	var existingID string
	for _, inst := range instances {
		if inst.Title == sessionTitle {
			existingID = inst.ID
			break
		}
	}

	var sessionID string
	existed := false
	if existingID != "" {
		sessionID = existingID
		existed = true
		for _, inst := range instances {
			if inst.ID != existingID {
				continue
			}
			inst.Tool = spec.Agent
			inst.Command = spec.DefaultCommand
			break
		}
		if !*jsonOutput {
			fmt.Printf("  [ok] Session '%s' already registered and synced to %s (ID: %s)\n", sessionTitle, spec.Agent, existingID[:8])
		}
	} else {
		dir, _ := session.ConductorNameDir(name)
		newInst := session.NewInstanceWithGroupAndTool(sessionTitle, dir, "conductor", spec.Agent)
		newInst.Command = spec.DefaultCommand
		newInst.IsConductor = true
		instances = append(instances, newInst)

		sessionID = newInst.ID
		if !*jsonOutput {
			fmt.Printf("  [ok] Session '%s' registered as %s (ID: %s)\n", sessionTitle, spec.Agent, newInst.ID[:8])
		}
	}

	// Always ensure conductor group is pinned to top
	groupTree := session.NewGroupTreeWithGroups(instances, groups)
	groupTree.DefaultMaxConcurrent = config.GroupDefaults.MaxConcurrent
	conductorGroup := groupTree.CreateGroup("conductor")
	conductorGroup.Order = -1

	if err := storage.SaveWithGroups(instances, groupTree); err != nil {
		fmt.Fprintf(os.Stderr, "Error saving session for %s: %v\n", resolvedProfile, err)
		os.Exit(1)
	}

	// Step 6: Install heartbeat timer (if heartbeat enabled and interval > 0)
	if heartbeatEnabled {
		interval := settings.GetHeartbeatInterval()
		if interval <= 0 {
			if !*jsonOutput {
				fmt.Println("  [skip] Heartbeat disabled (interval = 0)")
			}
		} else {
			if err := session.InstallHeartbeatScript(name, resolvedProfile); err != nil {
				fmt.Fprintf(os.Stderr, "Warning: failed to install heartbeat script: %v\n", err)
			} else if err := session.InstallHeartbeatDaemon(name, resolvedProfile, interval); err != nil {
				fmt.Fprintf(os.Stderr, "Warning: failed to install heartbeat daemon: %v\n", err)
			} else if !*jsonOutput {
				fmt.Printf("  [ok] Heartbeat timer installed (every %d min)\n", interval)
			}
		}
	}

	// Step 7: Install bridge (if Telegram, Slack, or Discord is configured)
	var plistPath string
	if telegramConfigured || slackConfigured || discordConfigured {
		if !*jsonOutput {
			fmt.Println()
			fmt.Println("Installing bridge...")
		}

		depsInstalled := installPythonDeps()

		if err := session.InstallBridgeScript(); err != nil {
			fmt.Fprintf(os.Stderr, "Error installing bridge.py: %v\n", err)
			os.Exit(1)
		}
		if !*jsonOutput {
			fmt.Println("[ok] bridge.py installed")
		}

		if !depsInstalled {
			// Don't register a launchd job that will crash-loop silently on
			// the missing imports. installPythonDeps() already printed an
			// actionable error block; surface a one-liner here too so the
			// final setup summary visibly mentions the gap.
			if !*jsonOutput {
				fmt.Println("[skip] Bridge daemon NOT installed (Python deps unavailable — see error above)")
				fmt.Println("       Re-run `agent-deck conductor setup <name>` after installing deps.")
			}
		} else {
			// Install daemon (platform-aware: launchd on macOS, systemd on Linux)
			daemonPath, err := session.InstallBridgeDaemon()
			if err != nil {
				fmt.Fprintf(os.Stderr, "Warning: failed to install bridge daemon: %v\n", err)
				condDir, _ := session.ConductorDir()
				fmt.Fprintf(os.Stderr, "Run manually: python3 %s/bridge.py\n", condDir)
			} else {
				plistPath = daemonPath
				if !*jsonOutput {
					fmt.Println("[ok] Bridge daemon loaded")
				}
			}
		}
	}

	// Step 8: Install transition notifier daemon (always-on status-driven notifications)
	var notifierDaemonPath string
	if daemonPath, err := session.InstallTransitionNotifierDaemon(); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: failed to install transition notifier daemon: %v\n", err)
		fmt.Fprintf(os.Stderr, "Tip: %s\n", session.TransitionNotifierDaemonHint())
	} else {
		notifierDaemonPath = daemonPath
		if !*jsonOutput {
			fmt.Println("[ok] Transition notifier daemon installed")
		}
	}

	// Output summary
	if *jsonOutput {
		data := map[string]any{
			"success":                 true,
			"agent":                   spec.Agent,
			"name":                    name,
			"profile":                 resolvedProfile,
			"session":                 sessionID,
			"existed":                 existed,
			"heartbeat":               heartbeatEnabled,
			"telegram":                telegramConfigured,
			"slack":                   slackConfigured,
			"discord":                 discordConfigured,
			"notifier_daemon_running": session.IsTransitionNotifierDaemonRunning(),
		}
		if plistPath != "" {
			data["daemon"] = plistPath
		}
		if notifierDaemonPath != "" {
			data["notifier_daemon"] = notifierDaemonPath
		}
		output, _ := json.MarshalIndent(data, "", "  ")
		fmt.Println(string(output))
		return
	}

	fmt.Println()
	fmt.Println("Conductor setup complete!")
	fmt.Println()
	fmt.Printf("  Name:      %s\n", name)
	fmt.Printf("  Agent:     %s\n", spec.Agent)
	fmt.Printf("  Profile:   %s\n", resolvedProfile)
	fmt.Printf("  Heartbeat: %v\n", heartbeatEnabled)
	if *description != "" {
		fmt.Printf("  Desc:      %s\n", *description)
	}
	fmt.Println()
	fmt.Println("Next steps:")
	if telegramConfigured || slackConfigured || discordConfigured {
		condDir, _ := session.ConductorDir()
		fmt.Printf("  agent-deck -p %s session start %s\n", resolvedProfile, sessionTitle)
		fmt.Println()
		if telegramConfigured {
			fmt.Println("  Test from Telegram: send /status to your bot")
		}
		if slackConfigured {
			fmt.Println("  Test from Slack: post a message in the configured channel")
		}
		if discordConfigured {
			fmt.Println("  Test from Discord: post a message in the configured channel or use /ad-status")
		}
		fmt.Printf("  View bridge logs:   tail -f %s/bridge.log\n", condDir)
	} else {
		fmt.Printf("  1. Start the conductor:  agent-deck -p %s session start %s\n", resolvedProfile, sessionTitle)
		fmt.Println("  2. Interact via the TUI: switch to the conductor session in the session list")
		fmt.Printf("  3. Or use the CLI:       agent-deck -p %s session send %s \"your message\"\n", resolvedProfile, sessionTitle)
		fmt.Println()
		fmt.Printf("  To add remote channels later: agent-deck -p %s conductor setup %s\n", resolvedProfile, name)
	}
}

// handleConductorTeardown stops conductors and optionally removes directories
func handleConductorTeardown(_ string, args []string) {
	fs := flag.NewFlagSet("conductor teardown", flag.ExitOnError)
	removeAll := fs.Bool("remove", false, "Remove conductor directories and sessions")
	allConductors := fs.Bool("all", false, "Teardown all conductors")
	jsonOutput := fs.Bool("json", false, "Output as JSON")

	fs.Usage = func() {
		fmt.Println("Usage: agent-deck conductor teardown <name> [options]")
		fmt.Println("       agent-deck conductor teardown --all [options]")
		fmt.Println()
		fmt.Println("Stop a conductor session and optionally remove its directory.")
		fmt.Println()
		fmt.Println("Arguments:")
		fmt.Println("  <name>    Conductor name to tear down")
		fmt.Println()
		fmt.Println("Options:")
		fs.PrintDefaults()
	}

	// Extract positional arg before flags
	var name string
	var flagArgs []string
	for _, arg := range args {
		if strings.HasPrefix(arg, "-") {
			flagArgs = append(flagArgs, arg)
		} else if name == "" {
			name = arg
		} else {
			flagArgs = append(flagArgs, arg)
		}
	}

	if err := fs.Parse(normalizeArgs(fs, flagArgs)); err != nil {
		os.Exit(1)
	}

	if !*allConductors && name == "" {
		fmt.Fprintln(os.Stderr, "Error: conductor name or --all is required")
		fmt.Fprintln(os.Stderr, "Usage: agent-deck conductor teardown <name> or --all")
		os.Exit(1)
	}

	// Auto-migrate before teardown so we can find legacy conductors
	runAutoMigration(*jsonOutput)

	// Determine which conductors to tear down
	var targets []session.ConductorMeta
	if *allConductors {
		var err error
		targets, err = session.ListConductors()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error listing conductors: %v\n", err)
			os.Exit(1)
		}
		if len(targets) == 0 {
			if *jsonOutput {
				fmt.Println(`{"success": true, "removed": 0}`)
			} else {
				fmt.Println("No conductors found.")
			}
			return
		}
	} else {
		meta, err := session.LoadConductorMeta(name)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: conductor %q not found: %v\n", name, err)
			os.Exit(1)
		}
		targets = []session.ConductorMeta{*meta}
	}

	// Step 1: Stop bridge daemon (only when tearing down all)
	if *allConductors {
		if session.IsBridgeDaemonRunning() {
			if !*jsonOutput {
				fmt.Println("Stopping bridge daemon...")
			}
			_ = session.UninstallBridgeDaemon()
			if !*jsonOutput {
				fmt.Println("[ok] Daemon stopped and removed")
			}
		}
		if session.IsTransitionNotifierDaemonRunning() {
			if !*jsonOutput {
				fmt.Println("Stopping transition notifier daemon...")
			}
			_ = session.UninstallTransitionNotifierDaemon()
			if !*jsonOutput {
				fmt.Println("[ok] Transition notifier daemon stopped and removed")
			}
		}
	}

	// Step 2: Stop and optionally remove each conductor
	var removed []string
	for _, meta := range targets {
		sessionTitle := session.ConductorSessionTitle(meta.Name)
		if !*jsonOutput {
			fmt.Printf("Stopping conductor: %s (profile: %s)\n", meta.Name, meta.Profile)
		}

		// Stop the session
		storage, err := session.NewStorageWithProfile(meta.Profile)
		if err == nil {
			instances, _, err := storage.LoadWithGroups()
			if err == nil {
				for _, inst := range instances {
					if inst.Title == sessionTitle {
						if inst.Exists() {
							_ = inst.Kill()
						}
						if !*jsonOutput {
							fmt.Printf("  [ok] %s stopped\n", sessionTitle)
						}
						break
					}
				}
			}
		}

		// Remove heartbeat timer
		_ = session.UninstallHeartbeatDaemon(meta.Name)

		// Optionally remove directory and session
		if *removeAll {
			if err := session.TeardownConductor(meta.Name); err != nil {
				if !*jsonOutput {
					fmt.Fprintf(os.Stderr, "  Warning: failed to remove dir for %s: %v\n", meta.Name, err)
				}
			} else if !*jsonOutput {
				fmt.Printf("  [ok] Removed directory for %s\n", meta.Name)
			}

			// Remove session from storage
			if storage != nil {
				instances, groups, err := storage.LoadWithGroups()
				if err == nil {
					var filtered []*session.Instance
					sessionRemoved := false
					for _, inst := range instances {
						if inst.Title == sessionTitle {
							sessionRemoved = true
							continue
						}
						filtered = append(filtered, inst)
					}
					if sessionRemoved {
						groupTree := session.NewGroupTreeWithGroups(filtered, groups)
						_ = storage.SaveWithGroups(filtered, groupTree)
						if !*jsonOutput {
							fmt.Printf("  [ok] Removed session '%s' from %s\n", sessionTitle, meta.Profile)
						}
					}
				}
			}
		}

		removed = append(removed, meta.Name)
	}

	// Clean up shared files if removing all
	if *allConductors && *removeAll {
		condDir, _ := session.ConductorDir()
		if condDir != "" {
			_ = os.Remove(filepath.Join(condDir, "bridge.py"))
			_ = os.Remove(filepath.Join(condDir, "bridge.log"))
			_ = os.Remove(filepath.Join(condDir, "CLAUDE.md"))
			_ = os.Remove(filepath.Join(condDir, "AGENTS.md"))
			_ = os.Remove(filepath.Join(condDir, "POLICY.md"))
			_ = os.Remove(filepath.Join(condDir, "LEARNINGS.md"))
			_ = os.Remove(condDir) // Remove dir if empty
		}
	}

	if *jsonOutput {
		output, _ := json.MarshalIndent(map[string]any{
			"success":  true,
			"removed":  *removeAll,
			"teardown": removed,
		}, "", "  ")
		fmt.Println(string(output))
		return
	}

	fmt.Println()
	fmt.Println("Teardown complete.")
	if !*removeAll {
		fmt.Println()
		fmt.Println("Conductor directories were kept. To remove them:")
		if *allConductors {
			fmt.Println("  agent-deck conductor teardown --all --remove")
		} else {
			fmt.Printf("  agent-deck conductor teardown %s --remove\n", name)
		}
	}
}

// handleConductorStatus shows conductor health
func handleConductorStatus(_ string, args []string) {
	fs := flag.NewFlagSet("conductor status", flag.ExitOnError)
	jsonOutput := fs.Bool("json", false, "Output as JSON")

	fs.Usage = func() {
		fmt.Println("Usage: agent-deck conductor status [name] [options]")
		fmt.Println()
		fmt.Println("Show conductor health status. If name is given, show that conductor only.")
		fmt.Println("Otherwise show all conductors.")
		fmt.Println()
		fmt.Println("Options:")
		fs.PrintDefaults()
	}

	// Extract positional arg before flags
	var name string
	var flagArgs []string
	for _, arg := range args {
		if strings.HasPrefix(arg, "-") {
			flagArgs = append(flagArgs, arg)
		} else if name == "" {
			name = arg
		} else {
			flagArgs = append(flagArgs, arg)
		}
	}

	if err := fs.Parse(normalizeArgs(fs, flagArgs)); err != nil {
		os.Exit(1)
	}

	// Auto-migrate before status check so stale heartbeat scripts self-heal even
	// when conductors are globally disabled in config.
	runAutoMigration(*jsonOutput)
	printConductorSplitBrainWarning(*jsonOutput)

	// Enabled-state is derived from conductor presence (#1361), not a config
	// flag. When no conductors exist, report disabled exactly as before so the
	// generated heartbeat.sh (which greps for `"enabled".*true`) and any other
	// consumers keep the same byte-stable contract.
	if !session.ConductorSystemActive() {
		if *jsonOutput {
			fmt.Println(`{"enabled": false}`)
		} else {
			fmt.Println("Conductor is not enabled.")
			fmt.Println("Run 'agent-deck conductor setup <name>' to configure it.")
		}
		return
	}

	// Get conductors to display
	var conductors []session.ConductorMeta
	if name != "" {
		meta, err := session.LoadConductorMeta(name)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: conductor %q not found: %v\n", name, err)
			os.Exit(1)
		}
		conductors = []session.ConductorMeta{*meta}
	} else {
		var err error
		conductors, err = session.ListConductors()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error listing conductors: %v\n", err)
			os.Exit(1)
		}
	}

	type conductorStatus struct {
		Name                 string `json:"name"`
		Agent                string `json:"agent"`
		Profile              string `json:"profile"`
		DirExists            bool   `json:"dir_exists"`
		SessionID            string `json:"session_id,omitempty"`
		SessionDone          bool   `json:"session_registered"`
		Running              bool   `json:"running"`
		Heartbeat            bool   `json:"heartbeat"`
		Description          string `json:"description,omitempty"`
		LastActivityAt       string `json:"last_activity_at,omitempty"`
		HeartbeatIdleMinutes int    `json:"heartbeat_idle_minutes"`
	}
	var statuses []conductorStatus

	for _, meta := range conductors {
		cs := conductorStatus{
			Name:                 meta.Name,
			Agent:                meta.GetAgent(),
			Profile:              meta.Profile,
			DirExists:            session.IsConductorSetup(meta.Name),
			Heartbeat:            meta.HeartbeatEnabled,
			Description:          meta.Description,
			HeartbeatIdleMinutes: meta.GetHeartbeatIdleMinutes(),
		}

		// Get last activity time across managed sessions (excludes conductor window).
		// Zero time means no data — omit rather than emit a spurious ancient timestamp.
		if lastActivity, err := session.GetConductorLastActivity(meta.Name, meta.Profile); err == nil && !lastActivity.IsZero() {
			cs.LastActivityAt = lastActivity.UTC().Format("2006-01-02T15:04:05Z07:00")
		}

		// Check session
		sessionTitle := session.ConductorSessionTitle(meta.Name)
		storage, err := session.NewStorageWithProfile(meta.Profile)
		if err == nil {
			instances, _, err := storage.LoadWithGroups()
			if err == nil {
				// Warm tmux + hook caches before UpdateStatus so we match
				// what the TUI and /api/menu show (issue #610).
				session.RefreshInstancesForCLIStatus(instances)
				for _, inst := range instances {
					if inst.Title == sessionTitle {
						cs.SessionID = inst.ID
						cs.SessionDone = true
						_ = inst.UpdateStatus()
						cs.Running = inst.Status == session.StatusRunning || inst.Status == session.StatusWaiting || inst.Status == session.StatusIdle
						break
					}
				}
			}
		}

		statuses = append(statuses, cs)
	}

	// Check bridge daemon
	daemonRunning := session.IsBridgeDaemonRunning()
	notifierRunning := session.IsTransitionNotifierDaemonRunning()

	if *jsonOutput {
		output, _ := json.MarshalIndent(map[string]any{
			"enabled":                 true,
			"conductors":              statuses,
			"daemon_running":          daemonRunning,
			"notifier_daemon_running": notifierRunning,
		}, "", "  ")
		fmt.Println(string(output))
		return
	}

	// Human-readable output
	fmt.Println("Conductor Status")
	fmt.Println("================")
	fmt.Println()

	if daemonRunning {
		fmt.Println("Bridge daemon: RUNNING")
	} else {
		fmt.Println("Bridge daemon: STOPPED")
	}
	if notifierRunning {
		fmt.Println("Notifier daemon: RUNNING")
	} else {
		fmt.Println("Notifier daemon: STOPPED")
	}
	fmt.Println()

	if len(statuses) == 0 {
		fmt.Println("  No conductors configured.")
		fmt.Println("  Run 'agent-deck conductor setup <name>' to create one.")
	}

	for _, cs := range statuses {
		var statusIcon, statusText string

		switch {
		case !cs.DirExists:
			statusIcon = "!"
			statusText = "not setup"
		case !cs.SessionDone:
			statusIcon = "!"
			statusText = "no session"
		case cs.Running:
			statusIcon = "●"
			statusText = "running"
		default:
			statusIcon = "○"
			statusText = "stopped"
		}

		hb := "on"
		if !cs.Heartbeat {
			hb = "off"
		}

		desc := ""
		if cs.Description != "" {
			desc = fmt.Sprintf("  %q", cs.Description)
		}

		fmt.Printf("  %s %s [%s] agent:%s heartbeat:%s  (%s)%s\n", statusIcon, cs.Name, cs.Profile, cs.Agent, hb, statusText, desc)
	}
	fmt.Println()

	// Hints
	if !daemonRunning {
		fmt.Printf("Tip: %s\n", session.BridgeDaemonHint())
	}
	if !notifierRunning {
		fmt.Printf("Tip: %s\n", session.TransitionNotifierDaemonHint())
	}
}

// handleConductorList lists all conductors
func handleConductorList(profile string, args []string) {
	fs := flag.NewFlagSet("conductor list", flag.ExitOnError)
	jsonOutput := fs.Bool("json", false, "Output as JSON")
	filterProfile := fs.String("profile", "", "Filter by profile")

	fs.Usage = func() {
		fmt.Println("Usage: agent-deck conductor list [options]")
		fmt.Println()
		fmt.Println("List all configured conductors.")
		fmt.Println()
		fmt.Println("Options:")
		fs.PrintDefaults()
	}

	if err := fs.Parse(normalizeArgs(fs, args)); err != nil {
		os.Exit(1)
	}

	// Auto-migrate
	runAutoMigration(*jsonOutput)
	printConductorSplitBrainWarning(*jsonOutput)

	var conductors []session.ConductorMeta
	var err error

	targetProfile := *filterProfile

	if targetProfile != "" {
		conductors, err = session.ListConductorsForProfile(targetProfile)
	} else {
		conductors, err = session.ListConductors()
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error listing conductors: %v\n", err)
		os.Exit(1)
	}

	if *jsonOutput {
		output, _ := json.MarshalIndent(map[string]any{
			"conductors": conductors,
		}, "", "  ")
		fmt.Println(string(output))
		return
	}

	if len(conductors) == 0 {
		fmt.Println("No conductors configured.")
		fmt.Println("Run 'agent-deck conductor setup <name>' to create one.")
		return
	}

	fmt.Println("Conductors:")
	fmt.Println()

	for _, meta := range conductors {
		// Check session status
		var statusText string
		sessionTitle := session.ConductorSessionTitle(meta.Name)
		storage, err := session.NewStorageWithProfile(meta.Profile)
		if err == nil {
			instances, _, err := storage.LoadWithGroups()
			if err == nil {
				// Warm tmux + hook caches before UpdateStatus so conductor
				// list matches the TUI and /api/menu view (issue #610).
				session.RefreshInstancesForCLIStatus(instances)
				found := false
				for _, inst := range instances {
					if inst.Title == sessionTitle {
						found = true
						_ = inst.UpdateStatus()
						if inst.Status == session.StatusRunning || inst.Status == session.StatusWaiting || inst.Status == session.StatusIdle {
							statusText = "running"
						} else {
							statusText = "stopped"
						}
						break
					}
				}
				if !found {
					statusText = "no session"
				}
			}
		}

		hb := "on"
		if !meta.HeartbeatEnabled {
			hb = "off"
		}

		desc := ""
		if meta.Description != "" {
			desc = fmt.Sprintf("  %q", meta.Description)
		}

		fmt.Printf("  %-12s [%s]  agent:%-6s heartbeat:%-3s  %-10s%s\n", meta.Name, meta.Profile, meta.GetAgent(), hb, statusText, desc)
	}
	fmt.Println()
}

// pipFailureKind classifies why a `pip install` invocation failed, so
// installPythonDeps() can emit an actionable error rather than the historical
// single-line stderr note that silently masked the PEP 668 case.
type pipFailureKind string

const (
	pipFailureNone   pipFailureKind = ""
	pipFailurePEP668 pipFailureKind = "pep668"
	pipFailureOther  pipFailureKind = "other"
)

// classifyPipFailure inspects captured pip stderr and returns the failure
// kind. Empty stderr maps to pipFailureNone (pip succeeded or wasn't run).
// The canonical PEP 668 marker is the literal phrase
// `externally-managed-environment`, emitted by pip on any interpreter whose
// stdlib ships an EXTERNALLY-MANAGED marker file (Homebrew, Debian/Ubuntu
// system Python).
func classifyPipFailure(stderr string) pipFailureKind {
	if stderr == "" {
		return pipFailureNone
	}
	if strings.Contains(stderr, "externally-managed-environment") {
		return pipFailurePEP668
	}
	return pipFailureOther
}

// pipFailureDiagnostic carries everything the formatter needs to render an
// actionable error block. Kept as a plain struct (no methods, no constructor)
// so tests can build instances directly.
type pipFailureDiagnostic struct {
	Kind            pipFailureKind
	InterpreterPath string   // sys.executable; empty if probing failed
	InterpreterVer  string   // sys.version.split()[0]; empty if probing failed
	Packages        []string // packages pip was asked to install
	HasMise         bool     // mise binary on PATH at install time
	RawStderr       string   // captured stderr from the failing pip call
}

// formatPipFailureMessage renders the user-facing error block. The PEP 668
// path lists three remediation options and labels exactly ONE as
// "recommended" — mise when available on PATH, otherwise the venv option.
// The Other path surfaces the raw pip stderr and a manual install command,
// without speculating on the cause.
func formatPipFailureMessage(d pipFailureDiagnostic) string {
	pkgs := strings.Join(d.Packages, " ")

	if d.Kind != pipFailurePEP668 {
		var b strings.Builder
		b.WriteString("⚠  Python dependencies install failed.\n\n")
		if d.RawStderr != "" {
			b.WriteString("   pip stderr:\n")
			for _, line := range strings.Split(strings.TrimRight(d.RawStderr, "\n"), "\n") {
				b.WriteString("     ")
				b.WriteString(line)
				b.WriteString("\n")
			}
			b.WriteString("\n")
		}
		b.WriteString("   Re-run `agent-deck conductor setup <name>`, or install manually:\n")
		fmt.Fprintf(&b, "     pip3 install %s\n", pkgs)
		return b.String()
	}

	pyDisplay := d.InterpreterPath
	if d.InterpreterVer != "" {
		pyDisplay = fmt.Sprintf("%s (%s)", d.InterpreterPath, d.InterpreterVer)
	}

	// Exactly one option carries the "recommended" label. mise wins when
	// detected; venv is the fallback recommendation otherwise.
	miseHeader := "1. Use a version-manager Python:"
	venvHeader := "2. Install into a dedicated venv (most isolated):"
	if d.HasMise {
		miseHeader = "1. Use a version-manager Python (recommended — mise detected on PATH):"
	} else {
		venvHeader = "2. Install into a dedicated venv (recommended — most isolated):"
	}

	var b strings.Builder
	b.WriteString("✗ Python dependencies could NOT be installed automatically.\n\n")
	b.WriteString("  Reason:  PEP 668 — externally-managed-environment\n")
	fmt.Fprintf(&b, "  Python:  %s\n", pyDisplay)
	fmt.Fprintf(&b, "  Needed:  %s\n\n", strings.Join(d.Packages, ", "))
	b.WriteString("  This Python interpreter is marked \"externally managed\" (common with\n")
	b.WriteString("  Homebrew and Debian/Ubuntu system Python), so `pip install --user`\n")
	b.WriteString("  is blocked by policy. The Telegram bridge cannot start until this\n")
	b.WriteString("  is resolved, so the launchd daemon was NOT installed.\n\n")
	b.WriteString("  Pick ONE of these and re-run `agent-deck conductor setup <name>`:\n\n")
	fmt.Fprintf(&b, "    %s\n", miseHeader)
	b.WriteString("         mise use -g python@<VERSION> && mise install\n")
	b.WriteString("         # <VERSION> is any Python 3.11+ — e.g. 3.12 or 3.13.\n")
	b.WriteString("         # agent-deck does not pin a specific version.\n\n")
	fmt.Fprintf(&b, "    %s\n", venvHeader)
	b.WriteString("         python3 -m venv ~/.agent-deck/conductor/.venv\n")
	fmt.Fprintf(&b, "         ~/.agent-deck/conductor/.venv/bin/pip install %s\n", pkgs)
	b.WriteString("         # (manual: edit ~/Library/LaunchAgents/com.agentdeck.conductor-bridge.plist\n")
	b.WriteString("         #  to point at ~/.agent-deck/conductor/.venv/bin/python3)\n\n")
	b.WriteString("    3. Override the policy (works, but the policy exists for a reason):\n")
	fmt.Fprintf(&b, "         python3 -m pip install --user --break-system-packages %s\n\n", pkgs)
	b.WriteString("  After fixing, verify with:  agent-deck conductor status\n")
	b.WriteString("  If the bridge still won't start: tail ~/.agent-deck/conductor/bridge.log\n")
	return b.String()
}

// installPythonDeps installs Python dependencies for the bridge.
// Returns true on success. On failure it prints a formatted, actionable error
// (PEP 668 gets a special-cased remediation block listing three fix options;
// other failures pass the raw pip stderr through) and returns false so the
// caller can skip the bridge daemon install rather than letting it crash-loop
// invisibly.
func installPythonDeps() bool {
	config, err := session.LoadUserConfig()
	packages := []string{"toml"}

	if err == nil && config != nil {
		if config.Conductor.Telegram.Token != "" {
			packages = append(packages, "aiogram")
		}
		if config.Conductor.Slack.BotToken != "" {
			packages = append(packages, "slack-bolt", "slack-sdk", "aiohttp")
		}
		if config.Conductor.Discord.BotToken != "" {
			packages = append(packages, "discord.py")
		}
	}

	// Fallback: if no specific integration detected, install all
	if len(packages) == 1 {
		packages = append(packages, "aiogram", "slack-bolt", "slack-sdk", "aiohttp", "discord.py")
	}

	// Try with --user first; fall back to no --user (venvs, containers).
	// We capture stderr on the second attempt so a failure can be classified
	// and surfaced with a remediation message.
	args := append([]string{"-m", "pip", "install", "--quiet", "--user"}, packages...)
	if err := exec.Command("python3", args...).Run(); err == nil {
		return true
	}
	var stderrBuf bytes.Buffer
	args = append([]string{"-m", "pip", "install"}, packages...)
	cmd := exec.Command("python3", args...)
	cmd.Stderr = &stderrBuf
	if err := cmd.Run(); err == nil {
		return true
	}

	diag := pipFailureDiagnostic{
		Kind:      classifyPipFailure(stderrBuf.String()),
		Packages:  packages,
		RawStderr: stderrBuf.String(),
	}
	diag.InterpreterPath, diag.InterpreterVer = probePythonInterpreter()
	if _, err := exec.LookPath("mise"); err == nil {
		diag.HasMise = true
	}

	if diag.Kind == pipFailureNone {
		// Pip exited non-zero but emitted nothing on stderr — treat as Other
		// so the user at least sees the install command.
		diag.Kind = pipFailureOther
	}
	fmt.Fprint(os.Stderr, formatPipFailureMessage(diag))
	return false
}

// probePythonInterpreter returns (path, version) by asking python3 to print
// sys.executable and sys.version. Empty strings on any probe failure — the
// formatter renders gracefully without them.
func probePythonInterpreter() (path, version string) {
	out, err := exec.Command("python3", "-c",
		"import sys; print(sys.executable); print(sys.version.split()[0])").Output()
	if err != nil {
		return "", ""
	}
	lines := strings.SplitN(strings.TrimSpace(string(out)), "\n", 2)
	if len(lines) >= 1 {
		path = strings.TrimSpace(lines[0])
	}
	if len(lines) >= 2 {
		version = strings.TrimSpace(lines[1])
	}
	return path, version
}

// printConductorHelp prints the conductor subcommand help
func printConductorHelp() {
	fmt.Println("Usage: agent-deck [-p profile] conductor <command>")
	fmt.Println()
	fmt.Println("Manage named conductor sessions for meta-agent orchestration.")
	fmt.Println("Multiple conductors can exist per profile.")
	fmt.Println()
	fmt.Println("Commands:")
	fmt.Println("  setup <name>     Set up a named conductor")
	fmt.Println("  teardown <name>  Stop and optionally remove a conductor (or --all)")
	fmt.Println("  status [name]    Show conductor health (all or specific)")
	fmt.Println("  list             List all configured conductors")
	fmt.Println("  move <name>      Move a conductor to another profile (--to-profile)")
	fmt.Println("  migrate-dir <path>  Relocate the conductor base dir (move homes + reconcile daemons)")
	fmt.Println("  help             Show this help")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  agent-deck -p work conductor setup ryan --description \"Ryan project\"")
	fmt.Println("  agent-deck -p work conductor setup review --agent codex --description \"Codex reviewer\"")
	fmt.Println("  agent-deck -p work conductor setup infra --no-heartbeat")
	fmt.Println("  agent-deck conductor list")
	fmt.Println("  agent-deck conductor status")
	fmt.Println("  agent-deck conductor teardown infra --remove")
	fmt.Println("  agent-deck conductor teardown --all --remove")
	fmt.Println("  agent-deck conductor move ryan --to-profile march")
	fmt.Println("  agent-deck conductor migrate-dir ~/vault/conductors          # dry-run plan")
	fmt.Println("  agent-deck conductor migrate-dir ~/vault/conductors --apply  # perform")
}

// printConductorSplitBrainWarning prints a one-line warning when [conductor].dir
// resolves to an empty base while the default base still holds conductor homes
// — the declarative-flip split-brain. Detection-only; suppressed in JSON mode.
func printConductorSplitBrainWarning(jsonOutput bool) {
	if jsonOutput {
		return
	}
	if msg, ok := session.DetectConductorDirSplitBrain(); ok {
		fmt.Fprintf(os.Stderr, "⚠  %s\n", msg)
	}
}

// bridgeDaemonInstalled reports whether a conductor bridge daemon is currently
// installed (launchd plist or systemd unit present on disk).
func bridgeDaemonInstalled() bool {
	if p, err := session.LaunchdPlistPath(); err == nil {
		if _, err := os.Stat(p); err == nil {
			return true
		}
	}
	if p, err := session.SystemdBridgeServicePath(); err == nil {
		if _, err := os.Stat(p); err == nil {
			return true
		}
	}
	return false
}

// handleConductorMigrateDir relocates the conductor base directory as one
// explicit transaction: move/merge homes old→new, set [conductor].dir, and
// reconcile path-baked artifacts (heartbeat scripts + daemons, bridge daemon)
// so launchd/systemd invoke the new paths. Defaults to a dry-run; --apply
// performs the move. This is the deliberate, destructive path the declarative
// [conductor].dir override intentionally avoids.
func handleConductorMigrateDir(_ string, args []string) {
	fs := flag.NewFlagSet("conductor migrate-dir", flag.ExitOnError)
	apply := fs.Bool("apply", false, "Perform the relocation (default is a dry-run that changes nothing)")
	force := fs.Bool("force", false, "Merge into an existing destination per-file (destination wins on conflicts) instead of skipping")
	from := fs.String("from", "", "Override the auto-detected source base directory")
	jsonOutput := fs.Bool("json", false, "Output as JSON")

	fs.Usage = func() {
		fmt.Println("Usage: agent-deck conductor migrate-dir <new-path> [options]")
		fmt.Println()
		fmt.Println("Relocate the conductor base directory: move conductor homes to <new-path>,")
		fmt.Println("set [conductor].dir, and reconcile path-baked heartbeat scripts/daemons and")
		fmt.Println("the bridge daemon so the OS service managers invoke the new paths.")
		fmt.Println()
		fmt.Println("Runs as a DRY-RUN unless --apply is given.")
		fmt.Println()
		fmt.Println("Options:")
		fs.PrintDefaults()
	}

	// Extract positional new-path before flags (mirrors status).
	var target string
	var flagArgs []string
	for _, arg := range args {
		if strings.HasPrefix(arg, "-") {
			flagArgs = append(flagArgs, arg)
		} else if target == "" {
			target = arg
		} else {
			flagArgs = append(flagArgs, arg)
		}
	}
	if err := fs.Parse(normalizeArgs(fs, flagArgs)); err != nil {
		os.Exit(1)
	}
	if strings.TrimSpace(target) == "" {
		fmt.Fprintln(os.Stderr, "Error: migrate-dir requires a target path")
		fmt.Fprintln(os.Stderr)
		fs.Usage()
		os.Exit(1)
	}

	res, err := session.MigrateConductorDir(session.ConductorDirMigrateOptions{
		Target: target,
		From:   *from,
		Apply:  *apply,
		Force:  *force,
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: migrate-dir failed: %v\n", err)
		os.Exit(1)
	}

	// Daemon reconcile (apply only, and only when the migration actually
	// committed — a refused migration mutated nothing, so there is nothing to
	// reload). This is the one place the launchctl/systemctl reload belongs — an
	// explicit user command, not routine list/status. Each installer is
	// idempotent (unload/write/load).
	var reloadedHeartbeats []string
	bridgeReloaded := false
	if *apply && !res.Refused {
		globalInterval := 0
		if cfg, cerr := session.LoadUserConfig(); cerr == nil {
			globalInterval = cfg.Conductor.GetHeartbeatInterval()
		}
		for _, name := range res.Conductors {
			meta, merr := session.LoadConductorMeta(name)
			if merr != nil || !meta.HeartbeatEnabled {
				continue
			}
			interval := meta.HeartbeatInterval
			if interval <= 0 {
				interval = globalInterval
			}
			if interval <= 0 {
				continue
			}
			if derr := session.InstallHeartbeatDaemon(name, meta.Profile, interval); derr != nil {
				fmt.Fprintf(os.Stderr, "Warning: failed to reload heartbeat daemon for %s: %v\n", name, derr)
				continue
			}
			reloadedHeartbeats = append(reloadedHeartbeats, name)
		}
		// Reload the bridge daemon only if one is already installed.
		if bridgeDaemonInstalled() {
			if _, derr := session.InstallBridgeDaemon(); derr != nil {
				fmt.Fprintf(os.Stderr, "Warning: failed to reload bridge daemon: %v\n", derr)
			} else {
				bridgeReloaded = true
			}
		}
	}

	if *jsonOutput {
		out := map[string]any{
			"dry_run":                 res.DryRun,
			"source":                  res.Source,
			"target":                  res.Target,
			"config_written":          res.ConfigWritten,
			"bridge_reinstalled":      res.BridgeReinstalled,
			"conductors":              res.Conductors,
			"actions":                 res.Actions,
			"refused":                 res.Refused,
			"blockers":                res.Blockers,
			"source_removal_warnings": res.SourceRemovalWarnings,
			"heartbeats_reloaded":     reloadedHeartbeats,
			"bridge_reloaded":         bridgeReloaded,
		}
		b, _ := json.MarshalIndent(out, "", "  ")
		fmt.Println(string(b))
		// An apply that refused to mutate is a failure for scripting purposes.
		if *apply && res.Refused {
			os.Exit(1)
		}
		return
	}

	printMigrateDirSummary(res, reloadedHeartbeats, bridgeReloaded)

	// An apply that refused to mutate exits non-zero so the operator (or a
	// script) sees it did NOT relocate anything.
	if *apply && res.Refused {
		os.Exit(1)
	}
}

// printMigrateDirSummary renders a human-readable migrate-dir result.
func printMigrateDirSummary(res *session.ConductorDirMigrateResult, reloadedHeartbeats []string, bridgeReloaded bool) {
	switch {
	case res.DryRun:
		fmt.Println("DRY-RUN — no changes made. Re-run with --apply to perform the relocation.")
	case res.Refused:
		fmt.Println("REFUSED — nothing was moved and [conductor].dir was NOT changed.")
	default:
		fmt.Println("Conductor dir relocation complete.")
	}
	fmt.Println()
	fmt.Printf("  Source: %s\n", res.Source)
	fmt.Printf("  Target: %s\n", res.Target)
	fmt.Println()

	anySkipped := false
	anyReject := false
	if len(res.Actions) == 0 {
		fmt.Println("  (nothing to move — source and target match or source is empty)")
	} else {
		var moved, merged, skipped, rejected, transient int
		for _, a := range res.Actions {
			label := a.Name
			if a.IsHome {
				label += " (conductor)"
			}
			switch a.Action {
			case "move":
				moved++
				fmt.Printf("  [move]   %s\n", label)
			case "merge":
				merged++
				note := ""
				if a.Conflict {
					note = " — existing destination files preserved"
				}
				fmt.Printf("  [merge]  %s%s\n", label, note)
			case "skip-exists":
				skipped++
				anySkipped = true
				fmt.Printf("  [skip]   %s — destination exists (use --force to merge)\n", label)
			case "reject-conflict":
				rejected++
				anyReject = true
				fmt.Printf("  [reject] %s — %s\n", label, a.Reason)
			case "skip-transient":
				transient++
			}
		}
		fmt.Println()
		fmt.Printf("  Summary: %d moved, %d merged, %d skipped, %d rejected, %d transient ignored\n",
			moved, merged, skipped, rejected, transient)
	}

	// Blockers explain why an apply refused (or why a dry-run would refuse).
	if len(res.Blockers) > 0 {
		fmt.Println()
		fmt.Println("  Blockers (the migration cannot proceed until these are resolved):")
		for _, b := range res.Blockers {
			fmt.Printf("    - %s\n", b)
		}
	}

	if !res.DryRun && !res.Refused {
		fmt.Println()
		if res.ConfigWritten {
			fmt.Println("  [ok] [conductor].dir written to config.toml")
		}
		if res.BridgeReinstalled {
			fmt.Println("  [ok] bridge.py reinstalled at new base")
		}
		if len(reloadedHeartbeats) > 0 {
			fmt.Printf("  [ok] heartbeat daemons reloaded: %s\n", strings.Join(reloadedHeartbeats, ", "))
		}
		if bridgeReloaded {
			fmt.Println("  [ok] bridge daemon reloaded")
		}
		if len(res.SourceRemovalWarnings) > 0 {
			fmt.Println()
			fmt.Println("  Warning: config committed and durable records are at the target, but some")
			fmt.Println("  sources could not be removed (harmless duplicates at the old base):")
			for _, w := range res.SourceRemovalWarnings {
				fmt.Printf("    - %s\n", w)
			}
		}
	}

	if res.DryRun && (anySkipped || anyReject) {
		fmt.Println()
		if anySkipped && !anyReject {
			fmt.Println("  Note: some destinations already exist; re-run with --apply --force to merge them.")
		} else {
			fmt.Println("  Note: this plan would be REFUSED as-is — resolve the blockers above first.")
		}
	}
}

// handleConductorMove migrates a conductor (session row + all child sessions
// + meta.json) to another profile (issue #928).
func handleConductorMove(sourceProfile string, args []string) {
	fs := flag.NewFlagSet("conductor move", flag.ExitOnError)
	toProfile := fs.String("to-profile", "", "Target profile (required)")
	force := fs.Bool("force", false, "Migrate even if the conductor or a worker is running")
	jsonOutput := fs.Bool("json", false, "Output as JSON")
	quiet := fs.Bool("quiet", false, "Minimal output")
	quietShort := fs.Bool("q", false, "Minimal output (short)")

	fs.Usage = func() {
		fmt.Println("Usage: agent-deck conductor move <name> --to-profile <profile> [--force]")
		fmt.Println()
		fmt.Println("Migrate a conductor session and all its worker sessions to another")
		fmt.Println("profile's DB, and update ~/.agent-deck/conductor/<name>/meta.json in lockstep.")
		fmt.Println()
		fmt.Println("Options:")
		fs.PrintDefaults()
	}

	if err := fs.Parse(normalizeArgs(fs, args)); err != nil {
		os.Exit(1)
	}

	out := NewCLIOutput(*jsonOutput, *quiet || *quietShort)

	if fs.NArg() < 1 {
		out.Error("conductor move requires <name>", ErrCodeInvalidOperation)
		fs.Usage()
		os.Exit(1)
	}
	if *toProfile == "" {
		out.Error("--to-profile is required", ErrCodeInvalidOperation)
		fs.Usage()
		os.Exit(1)
	}

	name := fs.Arg(0)
	result, err := session.MigrateConductorToProfile(
		name, sourceProfile, *toProfile,
		session.ProfileMigrateOptions{Force: *force},
	)
	if err != nil {
		exitCode := ErrCodeInvalidOperation
		hint := ""
		switch {
		case errors.Is(err, session.ErrProfileMissing):
			exitCode = ErrCodeNotFound
		case errors.Is(err, session.ErrSessionRunning):
			hint = " (stop the conductor/workers first, or re-run with --force)"
		}
		out.Error(fmt.Sprintf("%v%s", err, hint), exitCode)
		os.Exit(1)
	}

	out.Success(
		fmt.Sprintf("Migrated conductor %q: profile %s → %s (%d sessions)",
			name, sourceProfile, *toProfile, len(result.MovedSessionIDs)),
		map[string]interface{}{
			"success":        true,
			"conductor":      name,
			"from_profile":   sourceProfile,
			"to_profile":     *toProfile,
			"sessions_moved": result.MovedSessionIDs,
			"cost_events":    result.MovedCostEvents,
			"watcher_events": result.MovedWatcherEvents,
			"groups_created": result.CreatedGroups,
			"meta_updated":   result.MetaUpdated,
		},
	)
}
